/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfacegrafica;

import java.awt.Color;

/**
 *
 * @author evand
 */
public class Tela03 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Tela03.class.getName());

    /**
     * Creates new form Tela03
     */
    public Tela03() {
          initComponents(); // RESOLVE O PROBLEMA DAS LABELS NÃO APARECER NA TELA

    lblTextoPrincipal.setForeground(Color.WHITE);
    lblTituloPequeno.setForeground(Color.WHITE);
    lblPequeno.setForeground(Color.WHITE);

    lblCEM.setForeground(Color.WHITE);
    lblCEM1.setForeground(Color.WHITE);
    lblCEM2.setForeground(Color.WHITE);

    

    setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnProximo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCEM = new javax.swing.JLabel();
        lblSeguro = new javax.swing.JLabel();
        lblRapido = new javax.swing.JLabel();
        lblCEM1 = new javax.swing.JLabel();
        lblSeguro1 = new javax.swing.JLabel();
        lblRede = new javax.swing.JLabel();
        lblCEM2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblSub = new javax.swing.JLabel();
        lblTituloPequeno = new javax.swing.JLabel();
        lblPequeno = new javax.swing.JLabel();
        lblTextoPrincipal = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(17, 17, 17));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnProximo.setBackground(new java.awt.Color(0, 120, 60));
        btnProximo.setForeground(new java.awt.Color(255, 255, 255));
        btnProximo.setText("Abra sua conta  ➜");
        btnProximo.setBorderPainted(false);
        btnProximo.setPreferredSize(new java.awt.Dimension(140, 45));
        btnProximo.addActionListener(this::btnProximoActionPerformed);
        jPanel1.add(btnProximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 290, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fototela3.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, -35, -1, 650));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logobranca (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 181, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-segurança-verificada-48.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        lblCEM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCEM.setForeground(new java.awt.Color(255, 255, 255));
        lblCEM.setText("Conexão Total");
        jPanel1.add(lblCEM, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        lblSeguro.setForeground(new java.awt.Color(255, 255, 255));
        lblSeguro.setText("Eficiente");
        jPanel1.add(lblSeguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, -1, -1));

        lblRapido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/relampago.png"))); // NOI18N
        jPanel1.add(lblRapido, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));

        lblCEM1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCEM1.setForeground(new java.awt.Color(255, 255, 255));
        lblCEM1.setText("100%");
        jPanel1.add(lblCEM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        lblSeguro1.setForeground(new java.awt.Color(255, 255, 255));
        lblSeguro1.setText("Seguro");
        jPanel1.add(lblSeguro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        lblRede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/rede.png"))); // NOI18N
        jPanel1.add(lblRede, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, -1, -1));

        lblCEM2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCEM2.setForeground(new java.awt.Color(255, 255, 255));
        lblCEM2.setText("Rápido");
        jPanel1.add(lblCEM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Na sua Mão");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, -1, -1));

        lblSub.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblSub.setForeground(new java.awt.Color(0, 153, 51));
        lblSub.setText("PRIMEIRO PASSO??");
        jPanel1.add(lblSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        lblTituloPequeno.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblTituloPequeno.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloPequeno.setText("Começe sua jornada com a FlowBank,");
        lblTituloPequeno.setToolTipText("");
        jPanel1.add(lblTituloPequeno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        lblPequeno.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblPequeno.setForeground(new java.awt.Color(255, 255, 255));
        lblPequeno.setText("o jeito inteligente de cuidar do seu dinheiro.");
        jPanel1.add(lblPequeno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        lblTextoPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        lblTextoPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTextoPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        lblTextoPrincipal.setText("PRONTO PARA DAR O ");
        jPanel1.add(lblTextoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        btnFechar.setBackground(new java.awt.Color(17, 17, 17));
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/left-arrow.png"))); // NOI18N
        btnFechar.addActionListener(this::btnFecharActionPerformed);
        jPanel1.add(btnFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        TelaCadastro telaCadastro = new TelaCadastro();
        telaCadastro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        new Tela02().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Tela03().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnProximo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCEM;
    private javax.swing.JLabel lblCEM1;
    private javax.swing.JLabel lblCEM2;
    private javax.swing.JLabel lblPequeno;
    private javax.swing.JLabel lblRapido;
    private javax.swing.JLabel lblRede;
    private javax.swing.JLabel lblSeguro;
    private javax.swing.JLabel lblSeguro1;
    private javax.swing.JLabel lblSub;
    private javax.swing.JLabel lblTextoPrincipal;
    private javax.swing.JLabel lblTituloPequeno;
    // End of variables declaration//GEN-END:variables
}
